name: "Sync Git Repo Action"
description: "Used for synchronizing a Git repository. Supports cross-platform."
author: "Neo Chen"

inputs:
  personal_access_token:
    description: "Personal Access Token (PAT) for Git authentication. Defaults to the GITHUB_TOKEN."
    default: ${{ secrets.GITHUB_TOKEN }}
  repository:
    description: "The repository to sync. Defaults to the current repository."
    default: ${{ github.repository }}
  branch:
    description: "The branch to sync. Defaults to the current branch."
    default: ${{ github.ref_name }}
  use_lfs:
    description: "Use Git LFS for large file support. Defaults to false."
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Synchronize Git Repository
      env:
        personal_access_token: ${{ inputs.personal_access_token }}
        repository: ${{ inputs.repository }}
        branch: ${{ inputs.branch }}
        use_lfs: ${{ inputs.use_lfs }}
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
      run: node ${{ github.action_path }}/sync-git-repo.js