name: "Sync Git Repository Action"
description: "Used for synchronizing a Git repository. Supports cross-platform."
author: "Neo Chen"

inputs:
  git_access_token:
    description: "Git Access Token for Authentication"
    required: true
  git_repo_name:
    description: "Repository Name"
    required: true
  git_branch:
    description: "Branch Name"
    required: true
  enable_git_lfs:
    description: Is enable Git LFS
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Sync Git Repository
      env:
        git_access_token: ${{ inputs.git_access_token }}
        git_repo_name: ${{ inputs.git_repo_name }}
        git_branch: ${{ inputs.git_branch }}
        enable_git_lfs: ${{ inputs.enable_git_lfs }}
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
      run: node ${{ github.action_path }}/sync-git-repository.js