name: "Sync Git Repo Action"
description: "Used for synchronizing a Git repository. Supports cross-platform."
author: "Neo Chen"

inputs:
  git_server:
    description: "The Git server to sync. Defaults to github.com."
    default: "github.com"
  use_ssh:
    description: "Use SSH for Git authentication. Defaults to false."
    default: "false"
  personal_access_token:
    description: "Personal Access Token (PAT) for Git authentication. Defaults to github.token."
    default: ${{ github.token }}
  repository:
    description: "The repository to sync. Defaults to github.repository."
    default: ${{ github.repository }}
  branch:
    description: "The branch to sync. Defaults to github.ref_name"
    default: ${{ github.ref_name }}
  use_lfs:
    description: "Use Git LFS for large file support. Defaults to false."
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Synchronize Git Repository
      env:
        git_server: ${{ inputs.git_server }}
        use_ssh: ${{ inputs.use_ssh }}
        personal_access_token: ${{ inputs.personal_access_token }}
        repository: ${{ inputs.repository }}
        branch: ${{ inputs.branch }}
        use_lfs: ${{ inputs.use_lfs }}
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
      run: node ${{ github.action_path }}/sync-git-repo.js