name: "Sync Git Repo Action"
description: "Used for synchronizing a Git repository. Supports cross-platform."
author: "Neo Chen"
inputs:
  repository_path:
    description: "The path to the repository to sync. Defaults to the current workspace."
    default: ${{ github.workspace }}
  git_server:
    description: "The Git server to sync. Defaults to github.com."
    default: "github.com"
  use_ssh:
    description: "Use SSH for Git authentication. Defaults to false."
    default: "false"
  personal_access_token:
    description: "Personal Access Token (PAT) for Git authentication. Defaults to github.token."
    default: ${{ github.token }}
  repository:
    description: "The repository to sync. Defaults to github.repository."
    default: ${{ github.repository }}
  ref_name:
    description: "The branch or tag to sync. Defaults to github.ref_name"
    default: ${{ github.ref_name }}
  deep_clean:
    description: "If true, uses the --ffdx flag to remove all untracked and ignored files; otherwise, uses -ffd to remove only untracked files. Defaults to false."
    default: "false"
  use_lfs:
    description: "Use Git LFS for large file support. Defaults to false."
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - name: Synchronize Git Repository
      env:
        repository_path : ${{ inputs.repository_path }}
        git_server: ${{ inputs.git_server }}
        use_ssh: ${{ inputs.use_ssh }}
        personal_access_token: ${{ inputs.personal_access_token }}
        repository: ${{ inputs.repository }}
        ref_name: ${{ inputs.ref_name }}
        deep_clean: ${{ inputs.deep_clean }}
        use_lfs: ${{ inputs.use_lfs }}
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
      working-directory: ${{ github.action_path }}
      run: npm run start