name: "Sync Git Repository Action"
description: "Used for synchronizing a Git repository. Supports cross-platform."
author: "Neo Chen"

inputs:
  access_token:
    description: "Git Access Token for Authentication"
  repo_name:
    description: "Repository Name"
    default: ${{ github.repository }}
  branch_name:
    description: "Branch Name"
    default: ${{ github.ref_name }}
  use_lfs:
    description: "Use Git LFS for large file support"
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Sync Git Repository
      env:
        access_token: ${{ inputs.access_token }}
        repo_name: ${{ inputs.repo_name }}
        branch_name: ${{ inputs.branch_name }}
        use_lfs: ${{ inputs.use_lfs }}
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
      run: node ${{ github.action_path }}/sync-git-repository.js